### ISSUE TITLE
PATHを消した後の動作

### ISSUE THREAD

**Issue by oonisidesu** [oonisidesu/minishell#131]
こちら対応した方がいいでしょうか？
個人的にはbuiltinでenvを動かしているので正常に処理させていいのかなと思っています。

PATHを消した後にenvコマンド
minishell：正常に表示
bash：エラー
```
minishell $ unset PATH
minishell $ env
TERM_SESSION_ID=...(以下略)
...

bash-3.2$ unset PATH
bash-3.2$ env
bash: env: No such file or directory
```

関連 #65

**Comment by ssmyg** [comment]
はい。bashと違ってbuiltinで実装しているので、このままで問題ないと思います。
