### ISSUE TITLE
シグナル関連の修正

### ISSUE THREAD

**Issue by ssmyg** [oonisidesu/minishell#20]
src/signal/signal.c

1. minishell自体の終了ステータスは最後の終了ステータスを返却する必要がある。

void	ctrl_d_clean_handler(t_minishell *minish)
```
exit(0);
```
↓
```
exit(minish->status_code);
```
に修正。

2. パイプの途中にビルトインがある場合、後半がkillされない可能性がある
```
sleep 10 | sleep 10 |  cd  | sleep 10 | sleep 10
```
上記の様な場合、下記ループが途中で止まってしまい、後半のプロセスがkillされない可能性がある。
```
while (node && node->pid > 0)
```

**Comment by oonisidesu** [comment]
メモ
1→すぐに変更可能
2→検討必要

2の修正方向定まり次第、修正してプルリク出す予定

**Comment by oonisidesu** [comment]
![Uploading スクリーンショット 2024-02-23 21.32.06.png…]()
