### ISSUE TITLE
envが無い時minishellが落ちる

### ISSUE THREAD

**Issue by ssmyg** [oonisidesu/minishell#48]
環境変数なしでminishellを起動した後、envするとminishellが落ちる
```
zsh $ env -i ./minishell
minishell $ env
malloc: Undefined error: 0
```

**Comment by oonisidesu** [comment]
メモ
- set_cmd_path関数でPATHを取得できなかった場合、split_pathでexitしている

**Comment by oonisidesu** [comment]
PATHがない場合、エラー文が異なる問題は #65 で対応のためclose
