### ISSUE TITLE
export 「#」対応

### ISSUE THREAD

**Issue by oonisidesu** [oonisidesu/minishell#62]
- 「#」以降は環境変数を定義しない
export AA=11 1 ##aa BB=22 2

```
bash-3.2$ export AA=11 1 ##aa BB=22 2
bash: export: `1': not a valid identifier
bash-3.2$ echo $AA
11
bash-3.2$ echo $BB

bash-3.2$
```

**Comment by ssmyg** [comment]
これってコメントアウトのことですよね？
やるとしたらパーサー側だけど、そもそもコメントアウトを実装する必要があるのかな？
少なくともexport側で実装する必要がないと思います。

**Comment by oonisidesu** [comment]
exportだけでなく、全てのコマンドで「#」の対応が必要になる。
影響範囲が大きいので対応しない方向。
